name: 8.3.8-bookworm

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set docker image label
        id: set_label
        run: |
          docker_image_path="webgrip/github-action-php"
          docker_image_tag="${{ github.workflow }}"
          echo "image_url=${docker_image_path}:${docker_image_tag}" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: images/php/8.3.8.8/bookworm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.set_label.outputs.image_url }}
    outputs:
      image-url: ${{ steps.set_label.outputs.image_url }}

  test-docker-image:
    uses: ./.github/workflows/test.yml
    with:
      docker-image: ${{ needs.build-and-push.outputs.image-url }}
