#TEst to run the dockerfile we just made, so that we know it's uppable

name: test

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string

jobs:
  test-docker-image:
    container: ${{ github.event.inputs.docker-image }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ls -la
        run: ls -la
